### ISSUE TITLE
Upgrade errors (unable to run bakthat upgrade_to_dump_truck)

### ISSUE THREAD

**Issue by tk422** [tsileo/bakthat#12]
Hey there I ran pip install bakthat -U

got this back:

root@dagobah:/home/xxxx# pip install bakthat --upgrade
Downloading/unpacking bakthat from http://pypi.python.org/packages/source/b/bakthat/bakthat-0.4.0.tar.gz#md5=40ce177b27f0b0407b9ce761e38434a3
  Downloading bakthat-0.4.0.tar.gz
  Running setup.py egg_info for package bakthat
Requirement already up-to-date: aaargh in /usr/local/lib/python2.6/dist-packages (from bakthat)
Requirement already up-to-date: boto in /usr/local/lib/python2.6/dist-packages (from bakthat)
Requirement already up-to-date: pycrypto in /usr/local/lib/python2.6/dist-packages (from bakthat)
Requirement already up-to-date: beefish in /usr/local/lib/python2.6/dist-packages (from bakthat)
Downloading/unpacking grandfatherson (from bakthat)
  Downloading GrandFatherSon-1.1.tar.gz
  Running setup.py egg_info for package grandfatherson
Downloading/unpacking dumptruck (from bakthat)
  Downloading dumptruck-0.1.4.tar.gz
  Running setup.py egg_info for package dumptruck
Downloading/unpacking byteformat (from bakthat)
  Downloading byteformat-0.2a.tar.gz
  Running setup.py egg_info for package byteformat
Downloading/unpacking pyyaml (from bakthat)
  Downloading PyYAML-3.10.zip (364kB): 364kB downloaded
  Running setup.py egg_info for package pyyaml
Downloading/unpacking sh (from bakthat)
  Downloading sh-1.08.tar.gz
  Running setup.py egg_info for package sh
Requirement already up-to-date: argparse in /usr/local/lib/python2.6/dist-packages (from aaargh->bakthat)
Installing collected packages: bakthat, grandfatherson, dumptruck, byteformat, pyyaml, sh
  Found existing installation: bakthat 0.3.7
    Uninstalling bakthat:
      Successfully uninstalled bakthat
  Running setup.py install for bakthat
    Installing bakthat script to /usr/local/bin
  Running setup.py install for grandfatherson
  Running setup.py install for dumptruck
    SyntaxError: ('invalid syntax', ('/usr/local/lib/python2.6/dist-packages/dumptruck/adapters_and_converters.py', 65, 24, '        d = {k: None for k in val}\n'))

```
SyntaxError: ('invalid syntax', ('/usr/local/lib/python2.6/dist-packages/dumptruck/convert.py', 99, 84, '    elif type(value) == dict and not set(map(type, value.keys())).issubset({unicode, str}):\n'))

SyntaxError: ('invalid syntax', ('/usr/local/lib/python2.6/dist-packages/dumptruck/dumptruck.py', 126, 35, "    column_names_expected = {'key', 'type', 'value'}\n"))
```

  Running setup.py install for byteformat
  Running setup.py install for pyyaml
    checking if libyaml is compilable
    gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -I/usr/include/python2.6 -c build/temp.linux-x86_64-2.6/check_libyaml.c -o build/temp.linux-x86_64-2.6/check_libyaml.o
    build/temp.linux-x86_64-2.6/check_libyaml.c:2:18: error: yaml.h: No such file or directory
    build/temp.linux-x86_64-2.6/check_libyaml.c: In function ‘main’:
    build/temp.linux-x86_64-2.6/check_libyaml.c:5: error: ‘yaml_parser_t’ undeclared (first use in this function)
    build/temp.linux-x86_64-2.6/check_libyaml.c:5: error: (Each undeclared identifier is reported only once
    build/temp.linux-x86_64-2.6/check_libyaml.c:5: error: for each function it appears in.)
    build/temp.linux-x86_64-2.6/check_libyaml.c:5: error: expected ‘;’ before ‘parser’
    build/temp.linux-x86_64-2.6/check_libyaml.c:6: error: ‘yaml_emitter_t’ undeclared (first use in this function)
    build/temp.linux-x86_64-2.6/check_libyaml.c:6: error: expected ‘;’ before ‘emitter’
    build/temp.linux-x86_64-2.6/check_libyaml.c:8: warning: implicit declaration of function ‘yaml_parser_initialize’
    build/temp.linux-x86_64-2.6/check_libyaml.c:8: error: ‘parser’ undeclared (first use in this function)
    build/temp.linux-x86_64-2.6/check_libyaml.c:9: warning: implicit declaration of function ‘yaml_parser_delete’
    build/temp.linux-x86_64-2.6/check_libyaml.c:11: warning: implicit declaration of function ‘yaml_emitter_initialize’
    build/temp.linux-x86_64-2.6/check_libyaml.c:11: error: ‘emitter’ undeclared (first use in this function)
    build/temp.linux-x86_64-2.6/check_libyaml.c:12: warning: implicit declaration of function ‘yaml_emitter_delete’

```
libyaml is not found or a compiler error: forcing --without-libyaml
(if libyaml is installed correctly, you may need to
 specify the option --include-dirs or uncomment and
 modify the parameter include_dirs in setup.cfg)
```

  Running setup.py install for sh
Successfully installed bakthat grandfatherson dumptruck byteformat pyyaml sh
Cleaning up...
root@dagobah:/home/xxxx# bakthat upgrade_to_dump_truck
usage: bakthat [-h]

```
           {info,restore,configure,show_glacier_inventory,backup_glacier_inventory,ls,restore_glacier_inventory,show_local_glacier_inventory,backup,delete}
           ...
```

bakthat: error: invalid choice: 'upgrade_to_dump_truck' (choose from 'info', 'restore', 'configure', 'show_glacier_inventory', 'backup_glacier_inventory', 'ls', 'restore_glacier_inventory', 'show_local_glacier_inventory', 'backup', 'delete')

**Comment by tsileo** [comment]
Ok, I see why:

``` python
SyntaxError: ('invalid syntax', ('/usr/local/lib/python2.6/dist-packages/dumptruck/adapters_and_converters.py', 65, 24, ' d = {k: None for k in val}\n'))
```

DumpTruck, a new requirements (a SQLite DB wrapper) use **dict comprehension** wich is not Python 2.6 compatible, you really can't upgrade to Python 2.7 ? I will check dumptruck repository to check if there is others Python 2.6 incompatibility.

Can you try importing dumptruck in a Python console:

```
$ python
>>> import dumptruck
```

Keep me updated, I will look at dumptruck code source.

**Comment by tk422** [comment]
Yeah looks like a 2.6 issue. Same thing when I try importing from the commandline. I'll see if i can upgrade 2.7 but its a production backup server so i am hesitant to touch it very much.

**Comment by tsileo** [comment]
Can you try this:

clone dumptruck https://github.com/scraperwiki/dumptruck and try make the following modification:

dumptruck/adapters_and_converters.py, line 65:

replace

```
d = {k: None for k in val}
```

by

```
d = {}
for k in val:
    d[k] = None
```

dumptruck/convert.py, line 99

replace

```
issubset({unicode, str})
```

by

```
issubset(set([unicode, str]))
```

umptruck/dumptruck.py line 126

replace

```
column_names_expected = {'key', 'type', 'value'}
```

by

```
column_names_expected = set(['key', 'type', 'value'])
```

Then

```
$ python setup.py install
```

**Comment by tk422** [comment]
Okay instead of modifying the dumptruck code (seems like thats a very bad idea to support) I just juryrigged 2.7.  Just so you know I would let people know that Ubuntu 10.04 (or anything on python 2.6 really isnt supported on this release)

**Comment by tsileo** [comment]
Hi,

Just to let you know that I ditched dumptruck for peewee (a much cleaner API and Python2.6 compatible), you can try update bakthat (0.4.4),

then run:

```
$ bakthat upgrade_from_shelve
```

And I think it should be OK, let me know if something goes wrong.
