### ISSUE TITLE
osx 10.7.5 supported?

### ISSUE THREAD

**Issue by pfitzmsn** [tsileo/bakthat#13]
running python 2.6.8 on 10.7.5... installs fine but get an error when trying to run configure.

  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/site-packages/dumptruck-0.1.4-py2.6.egg/dumptruck/dumptruck.py", line 126
    column_names_expected = {'key', 'type', 'value'}

**Comment by tsileo** [comment]
The issue comes from Python 2.6 and not OSX, I will ditch DumpTruck (the only requirement not Python 2.6 compatible) in favor of [peewee](http://peewee.readthedocs.org/en/latest/index.html).

The update should be available soon, I keep you updated !

**Comment by pfitzmsn** [comment]
awesome. thanks. i didnt see the docs on how to set up a central server
based on mysql... but i did not look very hard either. would this need to
be done through the API?

-pf

ps - sorry i am more of sys admin than dev so thanks for answering my
questions.

**Comment by tsileo** [comment]
I released bakthat 0.4.3 and now it should be Python2.6 compatible, keep me updated.

About the sync server, I haven't pushed yet my default implementation (next week I hope), but it will require MongoDB, not MySQL.

Let me know if you have any questions/feebacks.

**Comment by pfitzmsn** [comment]
looks it is still trying to use dumptruck?

File
"/opt/local/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/site-packages/bakthat-0.4.3-py2.6.egg/bakthat/models.py",
line 207, in switch_from_dt_to_peewee
    import dumptruck
  File
"/opt/local/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/site-packages/dumptruck-0.1.4-py2.6.egg/dumptruck/**init**.py",
line 25, in <module>
    from dumptruck import *
  File
"/opt/local/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/site-packages/dumptruck-0.1.4-py2.6.egg/dumptruck/dumptruck.py",
line 126
    column_names_expected = {'key', 'type', 'value'}

**Comment by tsileo** [comment]
You're right, my bad... I think I fixed it, can you try to update to 0.4.4 ?

Thanks !

**Comment by pfitzmsn** [comment]
boom... you got it. thank you. let me know when the centralized central
comes out!!

-pf

**Comment by tsileo** [comment]
Hi,

here is a basic synchronization server I use it for a month with 4 clients, it seems to works well, let me know if you need help getting it running of if you encounter any issue : https://github.com/tsileo/bakthat-syncserver

Keep me updated !
