### ISSUE TITLE
Incremental backups?

### ISSUE THREAD

**Issue by axolx** [tsileo/bakthat#16]
Does bakthat support incremental backups (e.g. duplicity)? Sorry if I missed this in the docs.

**Comment by tsileo** [comment]
No you're right, at this time bakthat doesn't support incremental backups, maybe one day if I found a clean python library, let me know if you have any idea/feedback.

Thanks !

**Comment by axolx** [comment]
Thanks for the quick reply. In the past, I've used Duplicity for incremental backups stored in S3 but I've only used it from the CLI, so I'm not sure what their API looks like.

**Comment by tsileo** [comment]
I looked at the code source, but the API is far from friendly for developers, since it's not aimed for developer to dig into. I also made a lot of search but I haven't find something I can implement myself, if you see something keep me updated !
