### ISSUE TITLE
not deleting .tgz files

### ISSUE THREAD

**Issue by decibelhertz** [tsileo/bakthat#17]
Using CentOS 6, python 2.6.  Installed like so:

> $ sudo yum groupinstall "Development Tools"
> $ sudo yum install python-pip python-devel PyYAML
> $ sudo pip-python install bakthat boto requests
> 
> $ uname -a
> Linux ****\* 2.6.32-279.1.1.el6.x86_64 #1 SMP Tue Jul 10 13:47:21 UTC 2012 x86_64 x86_64 x86_64 GNU/Linux

Python info:

> Name        : python
> Arch        : x86_64
> Version     : 2.6.6
> Release     : 36.el6
> Size        : 20 M
> Repo        : installed
> From repo   : base

Set $TMP per the docs, e.g. `export TMP=/scr/day`.
... but when I upload to Glacier, my temporary file is not purged once the transfer is complete.  I aim to move ~500 archives, each 4-12GB.  So, my staging disk will fill up if I do this programmatically.  Workaround is to blindly delete $TMP/tmp\* in my loop.

E.G. of my issue.

> $ ls -l $TMP/tmp*
> 
> $ bakthat backup -p TA -t test -d glacier --prompt no /root/baler14.log 
> Backing up /root/baler14.log
> Compressing...
> Uploading...
> 
> $ echo $?
> 0
> 
> $ ls -l $TMP/tmp*
> -rw-------. 1 user   group 276 Apr  1 16:43 tmpjEV6ZM

**Comment by tsileo** [comment]
Thanks for the feedback, I have an idea why this happen, I think it's a Python 2.6 related issue, I will try a fix today, I keep updated !

**Comment by decibelhertz** [comment]
I figured it was a 2.6 issue.  Happy to try the change when you're ready.  Cheers.

**Comment by tsileo** [comment]
The bug should be solved, I haven't updated bakthat on pypi yet, but you can install it from source.
And it was not a Python 2.6 issue, I introduced the bug when adding handling of already compressed file.

Let me know if you have any other issue, question, or suggestion.

Thanks !

**Comment by decibelhertz** [comment]
Thanks much.  I'll try from source in a couple hours.
