### ISSUE TITLE
How much control do we have over the GFS scheme

### ISSUE THREAD

**Issue by stephantual** [tsileo/bakthat#28]
Hi, now that the GFS issue has been resolved, I find myself in a bit of a pickle, with rotate() deleting all my backups for the current day except for the first one.

So for example, if I backup 24 times a day on the hour, it seems to only keep the one that took place at 1am that day, and discards everything that came afterwards, INCLUDING the current backup :(

Would a better solution in my case be perhaps to somehow use delete_older_than , at least I'd keep my 48 backups for the last 2 days, and nevermind using GFS?

Is it possible to use delete_older_than with a tag? That way I could keep some backups for longer than others.

Cheers!

**Comment by tsileo** [comment]
I think the GFS scheme (at least, the implementation provided by https://pypi.python.org/pypi/GrandFatherSon) is not the best solution for your need.

<code>delete_older_than</code> with tags can be a clever way to solve your issue, it doesn't support tags yet but I think it good idea, I will implement this anyway.

I'm wondering whether <code>delete_older_than</code> + tags is enough (I think it would be painful to manage tags) or if bakthat need a <code>RotationScheme</code> class user can subclass for creating complex rotation scheme (with helpers) like your case.

I'll try to think how I could implement a <code>RotationScheme</code> class, I keep you updated soon !

Thanks for your feedback!

**Comment by tsileo** [comment]
I will not implement a <code>RotationScheme</code> class, but I added tags support for <code>delete_older_than</code> on my todo list.

I dug into the [GrandFatherSon documentation](https://pypi.python.org/pypi/GrandFatherSon), I think I found why it gone wrong, <code>to_delete</code> function from GrandFatherSon has a <code>hours</code> parameters, so calling rotate with your previous roratation config + <code>hours=1</code> will keep 1 backup per hour.

I will update how the rotation config is stored, what do you think ?

**Comment by tsileo** [comment]
I find the good GFS scheme for you ! Here are the good parameters: <code>hours=48, weeks=4, months=12</code>, check out my IPython notebook debug: http://nbviewer.ipython.org/5538987

I will let user override GFS settings in <code>BakHelper</code> <code>rotate</code> method, I keep you updated !

**Comment by tsileo** [comment]
I just released bakthat 0.5.4, just replace <code>days: 2</code> by <code>hours: 48</code> in your configuration file, and I think this time, it should be good.

Keep me updated !

**Comment by stephantual** [comment]
Amazing, this works very well indeed! Thank you again!
