### ISSUE TITLE
Is there something in bakthat that would prevent logging from preserving its format string?

### ISSUE THREAD

**Issue by stephantual** [tsileo/bakthat#29]
Hi, am using:

```
logging.basicConfig(format='%(asctime)s - %(levelname)s - %(message)s', datefmt='%d/%m/%Y %H:%M:%S', level=getattr(logging, options.loglevel.upper()))

logging.info('Starting %s v%s, environment: %s, loglevel: %s' % (__file__, __version__, STRENV, options.loglevel.upper()))
```

.... with good success in all my scripts, but within the ones that leverage bakthat for some reason the format is completely ignored.

I suspect it's to do with a conflict in logger name, however I'm afraid I'm not yet enough of an expert to be 100% of this.

**Comment by tsileo** [comment]
I think it's my bad, I made some changes recently, I'm always trying to improve bakthat logger I will take a look at your issue soon.

Thanks!

**Comment by stephantual** [comment]
That's indeed working as intended now. Thank you very much!
