### ISSUE TITLE
trying to automate bakthat

### ISSUE THREAD

**Issue by anth1y** [tsileo/bakthat#32]
So I'm trying to write a script (for cron) that will call bakthat. so the obvious issue that I am having is having to input the password. IS there a way to save the password to a config file somehow?  

Thanks

Oh I tested bakthat out on a few files and it works great ... I'm waiting to use it on my office's backups.

**Comment by tsileo** [comment]
Hi,

From the [docs](http://docs.bakthat.io/en/latest/user_guide.html#backup):

Since version 0.5.2, you can set the password with BAKTHAT_PASSWORD environment variable.

```
$ BAKTHAT_PASSWORD=mypassword bakthat backup myfile
```

You should also check out [bakserver](http://bakserver.bakthat.io), I will release it soon.

Also, let me know if you have any other issue/feedback.

Thanks!

**Comment by anth1y** [comment]
actually I tried that and it didnt work...

On Fri, May 24, 2013 at 11:53 AM, Thomas Sileo notifications@github.comwrote:

> Hi,
> 
> From the docs http://docs.bakthat.io/en/latest/user_guide.html#backup:
> 
> Since version 0.5.2, you can set the password with BAKTHAT_PASSWORD
> environment variable.
> 
> $ BAKTHAT_PASSWORD=mypassword bakthat backup myfile
> 
> You should also check out bakserver http://bakserver.bakthat.io, I will
> release it soon.
> 
> Also, let me know if you have any other issue/feedback.
> 
> Thanks!
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/tsileo/bakthat/issues/32#issuecomment-18422712
> .

## 

Anthony Riley II
(415)407.9687
Linux user  #521929
http://counter.li.org/!

**Comment by tsileo** [comment]
It's really weird, because it works well on my servers. Are you running bakthat 0.5.4 ? Which OS are you using ?

Also, have you tried this:

```
$ export BAKTHAT_PASSWORD=yourpassword
$ bakthat backup yourfile
```

**Comment by tsileo** [comment]
Keep me updated!

**Comment by matthewp** [comment]
Is there a flag if we don't want a password?
