### ISSUE TITLE
configuration bakthat problem

### ISSUE THREAD

**Issue by SnAFKe** [tsileo/bakthat#37]
How i can install as mysql?

This is what i do.
# python setup.py install

running install
running bdist_egg
running egg_info
writing requirements to bakthat.egg-info/requires.txt
writing bakthat.egg-info/PKG-INFO
writing top-level names to bakthat.egg-info/top_level.txt
writing dependency_links to bakthat.egg-info/dependency_links.txt
writing entry points to bakthat.egg-info/entry_points.txt
reading manifest file 'bakthat.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no files found matching 'test'
writing manifest file 'bakthat.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
creating build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/bakthat
copying build/lib/bakthat/models.py -> build/bdist.linux-x86_64/egg/bakthat
copying build/lib/bakthat/sync_wip.py -> build/bdist.linux-x86_64/egg/bakthat
copying build/lib/bakthat/utils.py -> build/bdist.linux-x86_64/egg/bakthat
copying build/lib/bakthat/backends.py -> build/bdist.linux-x86_64/egg/bakthat
copying build/lib/bakthat/helper.py -> build/bdist.linux-x86_64/egg/bakthat
copying build/lib/bakthat/sync.py -> build/bdist.linux-x86_64/egg/bakthat
copying build/lib/bakthat/plugin.py -> build/bdist.linux-x86_64/egg/bakthat
copying build/lib/bakthat/**init**.py -> build/bdist.linux-x86_64/egg/bakthat
copying build/lib/bakthat/conf.py -> build/bdist.linux-x86_64/egg/bakthat
byte-compiling build/bdist.linux-x86_64/egg/bakthat/models.py to models.pyc
byte-compiling build/bdist.linux-x86_64/egg/bakthat/sync_wip.py to sync_wip.pyc
byte-compiling build/bdist.linux-x86_64/egg/bakthat/utils.py to utils.pyc
byte-compiling build/bdist.linux-x86_64/egg/bakthat/backends.py to backends.pyc
byte-compiling build/bdist.linux-x86_64/egg/bakthat/helper.py to helper.pyc
byte-compiling build/bdist.linux-x86_64/egg/bakthat/sync.py to sync.pyc
byte-compiling build/bdist.linux-x86_64/egg/bakthat/plugin.py to plugin.pyc
byte-compiling build/bdist.linux-x86_64/egg/bakthat/**init**.py to **init**.pyc
byte-compiling build/bdist.linux-x86_64/egg/bakthat/conf.py to conf.pyc
creating build/bdist.linux-x86_64/egg/EGG-INFO
copying bakthat.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying bakthat.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying bakthat.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying bakthat.egg-info/entry_points.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying bakthat.egg-info/not-zip-safe -> build/bdist.linux-x86_64/egg/EGG-INFO
copying bakthat.egg-info/requires.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying bakthat.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
creating 'dist/bakthat-0.6.0-py2.7.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing bakthat-0.6.0-py2.7.egg
removing '/usr/lib64/python2.7/site-packages/bakthat-0.6.0-py2.7.egg' (and everything under it)
creating /usr/lib64/python2.7/site-packages/bakthat-0.6.0-py2.7.egg
Extracting bakthat-0.6.0-py2.7.egg to /usr/lib64/python2.7/site-packages
bakthat 0.6.0 is already the active version in easy-install.pth
Installing bakthat script to /usr/bin

Installed /usr/lib64/python2.7/site-packages/bakthat-0.6.0-py2.7.egg
Processing dependencies for bakthat==0.6.0
Searching for Events==0.1.0
Best match: Events 0.1.0
Processing Events-0.1.0-py2.7.egg
Events 0.1.0 is already the active version in easy-install.pth

Using /usr/lib64/python2.7/site-packages/Events-0.1.0-py2.7.egg
Searching for requests==1.2.3
Best match: requests 1.2.3
Processing requests-1.2.3-py2.7.egg
requests 1.2.3 is already the active version in easy-install.pth

Using /usr/lib64/python2.7/site-packages/requests-1.2.3-py2.7.egg
Searching for sh==1.08
Best match: sh 1.08
Processing sh-1.08-py2.7.egg
sh 1.08 is already the active version in easy-install.pth

Using /usr/lib64/python2.7/site-packages/sh-1.08-py2.7.egg
Searching for PyYAML==3.10
Best match: PyYAML 3.10
Processing PyYAML-3.10-py2.7-linux-x86_64.egg
PyYAML 3.10 is already the active version in easy-install.pth

Using /usr/lib64/python2.7/site-packages/PyYAML-3.10-py2.7-linux-x86_64.egg
Searching for byteformat==0.2a
Best match: byteformat 0.2a
Processing byteformat-0.2a-py2.7.egg
byteformat 0.2a is already the active version in easy-install.pth

Using /usr/lib64/python2.7/site-packages/byteformat-0.2a-py2.7.egg
Searching for peewee==2.1.2
Best match: peewee 2.1.2
Processing peewee-2.1.2-py2.7.egg
peewee 2.1.2 is already the active version in easy-install.pth
Installing pwiz.py script to /usr/bin

Using /usr/lib64/python2.7/site-packages/peewee-2.1.2-py2.7.egg
Searching for GrandFatherSon==1.1
Best match: GrandFatherSon 1.1
Processing GrandFatherSon-1.1-py2.7.egg
GrandFatherSon 1.1 is already the active version in easy-install.pth

Using /usr/lib64/python2.7/site-packages/GrandFatherSon-1.1-py2.7.egg
Searching for beefish==0.1.1
Best match: beefish 0.1.1
Processing beefish-0.1.1-py2.7.egg
beefish 0.1.1 is already the active version in easy-install.pth
Installing beefish.py script to /usr/bin

Using /usr/lib64/python2.7/site-packages/beefish-0.1.1-py2.7.egg
Searching for pycrypto==2.6
Best match: pycrypto 2.6
Processing pycrypto-2.6-py2.7-linux-x86_64.egg
pycrypto 2.6 is already the active version in easy-install.pth

Using /usr/lib64/python2.7/site-packages/pycrypto-2.6-py2.7-linux-x86_64.egg
Searching for boto==2.9.6
Best match: boto 2.9.6
Processing boto-2.9.6-py2.7.egg
boto 2.9.6 is already the active version in easy-install.pth
Installing mturk script to /usr/bin
Installing cwutil script to /usr/bin
Installing cfadmin script to /usr/bin
Installing sdbadmin script to /usr/bin
Installing elbadmin script to /usr/bin
Installing cq script to /usr/bin
Installing bundle_image script to /usr/bin
Installing lss3 script to /usr/bin
Installing dynamodb_dump script to /usr/bin
Installing fetch_file script to /usr/bin
Installing asadmin script to /usr/bin
Installing list_instances script to /usr/bin
Installing launch_instance script to /usr/bin
Installing glacier script to /usr/bin
Installing kill_instance script to /usr/bin
Installing instance_events script to /usr/bin
Installing taskadmin script to /usr/bin
Installing s3put script to /usr/bin
Installing route53 script to /usr/bin
Installing dynamodb_load script to /usr/bin
Installing pyami_sendmail script to /usr/bin

Using /usr/lib64/python2.7/site-packages/boto-2.9.6-py2.7.egg
Searching for aaargh==0.4
Best match: aaargh 0.4
Processing aaargh-0.4-py2.7.egg
aaargh 0.4 is already the active version in easy-install.pth

Using /usr/lib64/python2.7/site-packages/aaargh-0.4-py2.7.egg
Searching for argparse==1.2.1
Best match: argparse 1.2.1
Processing argparse-1.2.1-py2.7.egg
argparse 1.2.1 is already the active version in easy-install.pth

Using /usr/lib64/python2.7/site-packages/argparse-1.2.1-py2.7.egg
Finished processing dependencies for bakthat==0.6.0

$ bakthat configure
Traceback (most recent call last):
  File "/usr/bin/bakthat", line 9, in <module>
    load_entry_point('bakthat==0.6.0', 'console_scripts', 'bakthat')()
  File "/usr/lib64/python2.7/site-packages/pkg_resources.py", line 346, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib64/python2.7/site-packages/pkg_resources.py", line 2516, in load_entry_point
    return ep.load()
  File "/usr/lib64/python2.7/site-packages/pkg_resources.py", line 2210, in load
    entry = **import**(self.module_name, globals(),globals(), ['**name**'])
  File "/usr/lib64/python2.7/site-packages/bakthat-0.6.0-py2.7.egg/bakthat/**init**.py", line 25, in <module>
    from bakthat.backends import GlacierBackend, S3Backend, RotationConfig, SwiftBackend
  File "/usr/lib64/python2.7/site-packages/bakthat-0.6.0-py2.7.egg/bakthat/backends.py", line 17, in <module>
    from bakthat.models import Inventory, Jobs
  File "/usr/lib64/python2.7/site-packages/bakthat-0.6.0-py2.7.egg/bakthat/models.py", line 1, in <module>
    import peewee
  File "build/bdist.linux-x86_64/egg/peewee.py", line 98, in <module>
peewee.ImproperlyConfigured: Either sqlite3, psycopg2 or MySQLdb must be installed

  File "build/bdist.linux-x86_64/egg/peewee.py", line 98, in <module>
peewee.ImproperlyConfigured: Either sqlite3, psycopg2 or MySQLdb must be installed <-- how mysql?

**Comment by tsileo** [comment]
Sorry for the delay, the issue comes from **sqlite3** missing, as bakthat doesn't rely on MySQL.

sqlite3 is a standard module, I think Python hasn't been compiled with sqlite3 support, I tried to look on Google, maybe you can try this: http://stackoverflow.com/a/14550136, I close the issue as this is not a bakthat related issue, but please keep me updated!

Thanks!
