### ISSUE TITLE
Support for prefixing a key name in S3 backend

### ISSUE THREAD

**Issue by alexkehayias** [tsileo/bakthat#58]
Would be great to add support for a prefix to add to uploading files to s3. This would allow organizing backups within an existing bucket nested in directories (in S3 it's just a key). 

Could add a configuration variable called prefix and check for a prefix any time you generate a key name (upload, download). How would this effect the restore behavior? Seems like changing upload/download/ls in backends would cover it. Would be happy to add work on this for S3.

**Comment by iurisilvio** [comment]
:+1:

I'm trying to use bakthat but I really need this feature.

As a side note, I expected the `--key` parameter to give me this feature, but looks like it is an access key to bakmanager.
