### ISSUE TITLE
Another issue with python 2.6

### ISSUE THREAD

**Issue by tk422** [tsileo/bakthat#6]
Get this when actually doing a glacier backup:

013-02-07 13:36:12,158 INFO: Backing up /xxx/xxxx/
Password (blank to disable encryption): 
Password confirmation: 
2013-02-07 13:36:15,826 INFO: Compressing...
Traceback (most recent call last):
  File "/usr/local/bin/bakthat", line 9, in <module>
    load_entry_point('bakthat==0.3.1', 'console_scripts', 'bakthat')()
  File "/usr/local/bin/bakthat.py", line 528, in main
    app.run()
  File "/usr/local/lib/python2.6/dist-packages/aaargh.py", line 157, in run
    return func(**kwargs)
  File "/usr/local/bin/bakthat.py", line 357, in backup
    with tarfile.open(fileobj=out, mode="w:gz") as tar:
AttributeError: 'TarFile' object has no attribute '**exit**'

Looks like another 2.6 issue http://stackoverflow.com/questions/6086603/statement-with-and-tarfile

**Comment by tsileo** [comment]
Hi,

I made an update, can you please install from source and tell me if everything is OK before I release 0.3.2 ?

``` bash
$ git clone https://github.com/tsileo/bakthat.git
$ cd bakthat
$ sudo python setup.py install
```

Thanks !

**Comment by tsileo** [comment]
I pushed the changes on pypi so you can also upgrade with pip/easy_install.

``` bash
$ pip install --upgrade bakthat
```

Let me know if everything is OK !
